name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout your repo
    - uses: actions/checkout@v4

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install system dependencies
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip unzip openjdk-11-jdk python3-pip git

    # Step 4: Install Python dependencies
    - name: Install Python packages
      run: |
        python3 -m pip install --upgrade pip
        pip install cython
        pip install buildozer==1.5.0
        pip install kivy_garden.joystick

    # Step 5: Build the APK
    - name: Build APK
      run: |
        cd DroneApp
        buildozer android debug

    # Step 6: Upload APK artifact
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: DroneApp-apk
        path: DroneApp/bin/*.apk
