name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            libffi-dev \
            libssl-dev \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            libxi-dev \
            libx11-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            libjpeg-dev \
            libfreetype6-dev \
            libpng-dev \
            pkg-config \
            libblas-dev \
            liblapack-dev \
            gfortran

      - name: Install pip dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install cython buildozer
          pip install requests numpy opencv-python

      - name: Build with Buildozer
        run: |
          buildozer android debug

      - name: Rename APK with version
        run: |
          APP_NAME="DroneApp"
          VERSION=$(grep "version =" buildozer.spec | cut -d'=' -f2 | xargs)
          mv bin/*.apk "bin/${APP_NAME}-v${VERSION}-debug.apk"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: DroneApp-APK
          path: bin/*.apk
