name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk zip unzip zlib1g-dev wget curl git

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython kivy

      - name: Clear previous Buildozer cache
        run: |
          rm -rf ~/.buildozer/android/platform/android-ndk-r25b
          rm -rf ~/.buildozer/android/platform/android-sdk
          buildozer android clean

      - name: Download Android SDK cmdline-tools
        run: |
          ANDROIDSDK=$HOME/.buildozer/android/platform/android-sdk
          mkdir -p $ANDROIDSDK/cmdline-tools
          cd $ANDROIDSDK/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mv cmdline-tools latest

      - name: Set environment variables
        run: |
          echo "ANDROIDSDK=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "ANDROIDNDK=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV
          echo "$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: DroneApp-APK
          path: bin/*.apk
