name: Build DroneApp APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 1: Install essential tools
    - name: Install required tools
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk unzip wget zip python3-pip python3-dev python3-setuptools python3-wheel git

    # Step 2: Install Buildozer + Cython
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install "buildozer==1.5.0" "cython<3.0" "setuptools<70"

    # Step 3: Cache entire Buildozer folder for incremental builds
    - name: Cache Buildozer folder
      uses: actions/cache@v3
      with:
        path: $HOME/.buildozer
        key: buildozer-cache-v1

    # Step 4: Setup Android SDK/NDK/Ant + Build-tools if missing
    - name: Setup Android SDK + Build-tools
      run: |
        export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
        mkdir -p $ANDROID_HOME/cmdline-tools

        # --- Download cmdline-tools if missing ---
        if [ ! -d "$ANDROID_HOME/cmdline-tools/latest" ]; then
          cd $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O tools.zip
          unzip -q tools.zip -d latest
          rm tools.zip
        fi

        # Export PATH including cmdline-tools/bin
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH

        # Verify sdkmanager exists
        ls -l $ANDROID_HOME/cmdline-tools/latest/bin/

        # Accept licenses
        yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses

        # Install platform-tools, build-tools, platforms
        sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-33" "build-tools;33.0.2"

        # --- Install NDK if missing ---
        if [ ! -d "$ANDROID_HOME/ndk/25.1.8937393" ]; then
          cd $ANDROID_HOME
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip -O ndk.zip
          unzip -q ndk.zip
          rm ndk.zip
          mkdir -p ndk
          mv android-ndk-r25b ndk/25.1.8937393
        fi

        # --- Install Ant if missing ---
        if [ ! -d "$ANDROID_HOME/ant/apache-ant-1.9.4" ]; then
          cd $ANDROID_HOME
          wget https://archive.apache.org/dist/ant/binaries/apache-ant-1.9.4-bin.zip -O ant.zip
          unzip -q ant.zip
          rm ant.zip
          mkdir -p ant
          mv apache-ant-1.9.4 ant/apache-ant-1.9.4
        fi

        # Export NDK and Ant paths
        export ANDROIDNDK=$ANDROID_HOME/ndk/25.1.8937393
        export ANT_HOME=$ANDROID_HOME/ant/apache-ant-1.9.4
        export PATH=$ANT_HOME/bin:$PATH

        # Verify aidl exists
        ls -l $ANDROID_HOME/build-tools/33.0.2/aidl

    # Step 5: Build debug APK
    - name: Build APK
      working-directory: DroneApp
      run: buildozer -v android debug

    # Step 6: Upload APK artifact
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: DroneApp-APK
        path: DroneApp/bin/*.apk
