name: Build DroneApp APK

on:
push:
branches:
- main
workflow_dispatch:

jobs:
build-apk:
runs-on: ubuntu-latest

steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  # 1️⃣ Install system dependencies for Buildozer
  - name: Install system dependencies
    run: |
      sudo apt-get update
      sudo apt-get install -y \
        zip unzip openjdk-17-jdk \
        autoconf automake libtool \
        pkg-config zlib1g-dev libncurses5-dev \
        libffi-dev libssl-dev git \
        python3-dev python3-setuptools python3-wheel curl

  # 2️⃣ Install Buildozer and its Python dependencies
  - name: Install Buildozer and Python dependencies
    run: |
      python3 -m pip install --upgrade pip
      pip install "buildozer==1.5.0" "cython<3.0" "setuptools<70"

  # 3️⃣ Setup Android SDK and accept licenses
  # This step sets up the SDK and makes the paths persistent for all subsequent steps.
  - name: Setup Android SDK and accept licenses
    run: |
      # Set Android SDK Home and add to a temporary path for this step
      export ANDROID_HOME=$HOME/android-sdk
      echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
      mkdir -p $ANDROID_HOME/cmdline-tools
      cd $ANDROID_HOME/cmdline-tools
      curl -fo tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
      unzip -o tools.zip
      mv cmdline-tools latest
      export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
      echo "PATH=$PATH" >> $GITHUB_ENV

      # Accept all licenses and install required SDKs and Build-Tools
      yes | sdkmanager --licenses
      sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"
      # Re-accept licenses after installing new components
      yes | sdkmanager --licenses

  # 4️⃣ Clean previous Buildozer cache
  - name: Clean Buildozer cache
    run: rm -rf ~/.buildozer

  # 5️⃣ Build the APK
  # NOTE: This assumes your Kivy project is in a subdirectory named 'DroneApp'.
  - name: Build APK
    working-directory: DroneApp
    run: buildozer -v android debug

  # 6️⃣ Prepare and upload the APK artifact
  - name: Upload APK artifact
    uses: actions/upload-artifact@v4
    with:
      name: DroneApp-APK
      path: DroneApp/bin/*.apk
