name: Build DroneApp APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 1: Install essential tools
    - name: Install required tools
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk unzip wget zip python3-pip python3-dev python3-setuptools python3-wheel git

    # Step 2: Install Buildozer + Cython
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install "buildozer==1.5.0" "cython<3.0" "setuptools<70"

    # Step 3: Install Android SDK command-line tools
    - name: Setup Android SDK
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O tools.zip
        unzip -q tools.zip -d temp
        rm tools.zip

        # Move extracted folder into "latest"
        mv temp/cmdline-tools latest
        rm -rf temp

        # Persist environment variables
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

    # Step 4: Debug - Verify sdkmanager exists and works
    - name: Verify sdkmanager
      run: |
        ls -R $HOME/android-sdk/cmdline-tools/latest/bin
        $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --version

    # Step 5: Accept licenses + Install Build Tools
    - name: Install SDK Packages
      run: |
        $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
        $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    # Step 6: Clean previous Buildozer cache
    - name: Clean Buildozer cache
      run: rm -rf ~/.buildozer

    # Step 7: Build debug APK
    - name: Build APK
      working-directory: DroneApp
      run: buildozer -v android debug

    # Step 8: Upload APK artifact
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: DroneApp-APK
        path: DroneApp/bin/*.apk
