name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3️⃣ Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip openjdk-11-jdk python3-pip git

      # 4️⃣ Install Buildozer and Cython
      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade pip
          pip install --upgrade buildozer==1.5.0
          pip install --upgrade cython

      # 5️⃣ Build APK
      - name: Build APK
        run: |
          cd DroneApp
          buildozer android debug

      # 6️⃣ Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DroneApp-apk
          path: DroneApp/bin/*.apk
