name: Build DroneApp APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:python3.10

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Python dependencies (Buildozer + Cython)
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install "buildozer==1.5.0" "cython<3.0" "setuptools<70"

      # Step 3: Clean previous build cache
      - name: Clean Buildozer cache
        run: rm -rf ~/.buildozer

      # Step 4: Build debug APK
      - name: Build Debug APK
        working-directory: DroneApp
        run: buildozer -v android debug

      # Step 5: Build release APK (signed)
      - name: Build Release APK
        working-directory: DroneApp
        env:
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }} # Base64 encoded .keystore
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_ALIAS_PASSWORD: ${{ secrets.ANDROID_KEY_ALIAS_PASSWORD }}
        run: |
          # Decode keystore
          echo $ANDROID_KEYSTORE | base64 --decode > my-release.keystore
          # Update buildozer.spec for signing
          sed -i "s|#android.release_keystore =|android.release_keystore = my-release.keystore|" buildozer.spec
          sed -i "s|#android.keystore_password =|android.keystore_password = $ANDROID_KEYSTORE_PASSWORD|" buildozer.spec
          sed -i "s|#android.keyalias_name =|android.keyalias_name = $ANDROID_KEY_ALIAS|" buildozer.spec
          sed -i "s|#android.keyalias_password =|android.keyalias_password = $ANDROID_KEY_ALIAS_PASSWORD|" buildozer.spec
          buildozer -v android release

      # Step 6: Prepare APK artifact
      - name: Prepare APK artifact
        run: |
          mkdir -p artifacts
          zip -j artifacts/DroneApp-APKs.zip DroneApp/bin/*.apk

      # Step 7: Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DroneApp-APK
          path: artifacts/DroneApp-APKs.zip
