name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repo
    - uses: actions/checkout@v4

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install system dependencies
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip unzip openjdk-17-jdk git python3-pip

    # Step 4: Install buildozer and Cython
    - name: Install Buildozer and Cython
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade buildozer==1.5.0 cython

    # Step 5: Build APK
    - name: Build APK
      run: |
        cd DroneApp
        buildozer android debug

    # Step 6: Upload APK as artifact
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: DroneApp-apk
        path: DroneApp/bin/*.apk
