name: Build DroneApp APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      PATH: ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ github.workspace }}/android-sdk/platform-tools:$PATH

    steps:
      # Step 1: Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            zip unzip tar openjdk-17-jdk \
            autoconf automake libtool \
            pkg-config zlib1g-dev libncurses5-dev \
            libffi-dev libssl-dev git \
            python3-dev python3-setuptools python3-wheel

      # Step 2: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 3: Install Buildozer + dependencies
      - name: Install Buildozer and dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install "buildozer==1.5.0" "cython<3.0" "setuptools<70"

      # Step 4: Setup Android SDK
      - name: Setup Android SDK
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          curl -fo tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip tools.zip
          mv cmdline-tools latest
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses || true
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      # Step 5: Clean Buildozer cache
      - name: Clean Buildozer cache
        run: rm -rf ~/.buildozer

      # Step 6: Build APK
      - name: Build APK
        working-directory: DroneApp
        run: buildozer -v android debug

      # Step 7: Upload APK with timestamp
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DroneApp-APK-${{ github.run_number }}
          path: DroneApp/bin/*.apk
