name: Build DroneApp Release APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      PATH: ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ github.workspace }}/android-sdk/platform-tools:$PATH

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y zip unzip openjdk-17-jdk autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libffi-dev libssl-dev git python3-dev python3-setuptools python3-wheel

    - name: Install Buildozer + Python dependencies
      run: |
        pip install --upgrade pip
        pip install "buildozer==1.5.0" "cython<3.0" "setuptools<70"

    - name: Clean Buildozer cache
      run: rm -rf ~/.buildozer

    - name: Setup Android SDK Command-line Tools
      run: |
        mkdir -p $ANDROID_HOME/cmdline-tools
        cd $ANDROID_HOME/cmdline-tools
        curl -fo tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip tools.zip -d latest
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Install Android SDK Platforms & Build-tools
      run: |
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Build Release APK
      working-directory: DroneApp
      run: |
        buildozer android clean
        buildozer android release

    - name: Sign APK (debug keystore)
      working-directory: DroneApp/bin
      run: |
        jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ~/.buildozer/android/platform/android-sdk/debug.keystore bin/DroneApp-release-unsigned.apk androiddebugkey -storepass android -keypass android
        $ANDROID_HOME/build-tools/33.0.2/zipalign -v 4 bin/DroneApp-release-unsigned.apk DroneApp-release.apk

    - name: Prepare APK artifact
      run: |
        mkdir -p artifacts
        cp DroneApp/bin/DroneApp-release.apk artifacts/
        zip -j artifacts/DroneApp-Release-APK.zip artifacts/DroneApp-release.apk

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: DroneApp-Release-APK
        path: artifacts/DroneApp-Release-APK.zip
