name: Build DroneApp APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 1: Install essential tools
    - name: Install required tools
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk unzip wget zip python3-pip python3-dev python3-setuptools python3-wheel git

    # Step 2: Install Buildozer + Cython
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install "buildozer==1.5.0" "cython<3.0" "setuptools<70"

    # Step 3: Install Android SDK command-line tools + Build-Tools
    - name: Setup Android SDK
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
        unzip -q tools.zip -d latest
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    # Step 4: Clean previous Buildozer cache
    - name: Clean Buildozer cache
      run: rm -rf ~/.buildozer

    # Step 5: Build debug APK
    - name: Build APK
      working-directory: DroneApp
      run: buildozer -v android debug

    # Step 6: Upload APK artifact
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: DroneApp-APK
        path: DroneApp/bin/*.apk
